spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create-drop
        connection:
          pool_size: 50
