spring:
  #   base de datos posta
  datasource:
    url: jdbc:mysql://localhost/facultad
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop

  server:
    error:
      include-message: always
      include-binding-errors: always